from PyQt5 import QtCore
from PyQt5.QtGui import QFont

def in_list(in_convert_list, _translate):
    #List IN
        item = in_convert_list.item(0)
        item.setText(_translate("MainWindow", "Distance"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial",weight=QFont.Bold))
        item = in_convert_list.item(1)
        item.setText(_translate("MainWindow", "millimeter[mm]"))
        item = in_convert_list.item(2)
        item.setText(_translate("MainWindow", "centimeter[cm]"))
        item = in_convert_list.item(3)
        item.setText(_translate("MainWindow", "decimeter[dm]"))
        item = in_convert_list.item(4)
        item.setText(_translate("MainWindow", "meter[m]"))
        item = in_convert_list.item(5)
        item.setText(_translate("MainWindow", "decameter[dam]"))
        item = in_convert_list.item(6)
        item.setText(_translate("MainWindow", "hectometer[hm]"))
        item = in_convert_list.item(7)
        item.setText(_translate("MainWindow", "kilometer[km]"))
        item = in_convert_list.item(8)
        item.setText(_translate("MainWindow", "Mass"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial",weight=QFont.Bold))
        item = in_convert_list.item(9)
        item.setText(_translate("MainWindow", "Miligram[mg]"))
        item = in_convert_list.item(10)
        item.setText(_translate("MainWindow", "Centigram[cg]"))
        item = in_convert_list.item(11)
        item.setText(_translate("MainWindow", "Decigram[dg]"))
        item = in_convert_list.item(12)
        item.setText(_translate("MainWindow", "Gram[g]"))
        item = in_convert_list.item(13)
        item.setText(_translate("MainWindow", "Decagram[dag]"))
        item = in_convert_list.item(14)
        item.setText(_translate("MainWindow", "Hectogram[hg]"))
        item = in_convert_list.item(15)
        item.setText(_translate("MainWindow", "Kilogram[kg]"))
        item = in_convert_list.item(16)
        item.setText(_translate("MainWindow", "Temperature"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial", weight = QFont.Bold))
        item = in_convert_list.item(17)
        item.setText(_translate("MainWindow", "Kelvin[K]"))
        item = in_convert_list.item(18)
        item.setText(_translate("MainWindow", "Celsius[°C]"))
        item = in_convert_list.item(19)
        item.setText(_translate("MainWindow", "Fahenheit[°F]"))
        item = in_convert_list.item(20)
        item.setText(_translate("MainWindow", "Newton[°N]"))
        item = in_convert_list.item(21)
        item.setText(_translate("MainWindow", "Réaumur[°Ré]"))

def out_list(out_convert_list, _translate):
        #LIST OUT
        item = out_convert_list.item(0)
        item.setText(_translate("MainWindow", "Distance"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial",weight=QFont.Bold))
        item = out_convert_list.item(1)
        item.setText(_translate("MainWindow", "millimeter[mm]"))
        item = out_convert_list.item(2)
        item.setText(_translate("MainWindow", "centimeter[cm]"))
        item = out_convert_list.item(3)
        item.setText(_translate("MainWindow", "decimeter[dm]"))
        item = out_convert_list.item(4)
        item.setText(_translate("MainWindow", "meter[m]"))
        item = out_convert_list.item(5)
        item.setText(_translate("MainWindow", "decameter[dam]"))
        item = out_convert_list.item(6)
        item.setText(_translate("MainWindow", "hectometer[hm]"))
        item = out_convert_list.item(7)
        item.setText(_translate("MainWindow", "kilometer[km]"))
        item = out_convert_list.item(8)
        item.setText(_translate("MainWindow", "Mass"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial",weight=QFont.Bold))
        item = out_convert_list.item(9)
        item.setText(_translate("MainWindow", "Miligram[mg]"))
        item = out_convert_list.item(10)
        item.setText(_translate("MainWindow", "Centigram[cg]"))
        item = out_convert_list.item(11)
        item.setText(_translate("MainWindow", "Decigram[dg]"))
        item = out_convert_list.item(12)
        item.setText(_translate("MainWindow", "Gram[g]"))
        item = out_convert_list.item(13)
        item.setText(_translate("MainWindow", "Decagram[dag]"))
        item = out_convert_list.item(14)
        item.setText(_translate("MainWindow", "Hectogram[hg]"))
        item = out_convert_list.item(15)
        item.setText(_translate("MainWindow", "Kilogram[kg]"))
        item = out_convert_list.item(16)
        item.setText(_translate("MainWindow", "Temperature"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        item.setFont(QFont("Arial", weight = QFont.Bold))
        item = out_convert_list.item(17)
        item.setText(_translate("MainWindow", "Kelvin[K]"))
        item = out_convert_list.item(18)
        item.setText(_translate("MainWindow", "Celsius[°C]"))
        item = out_convert_list.item(19)
        item.setText(_translate("MainWindow", "Fahenheit[°F]"))
        item = out_convert_list.item(20)
        item.setText(_translate("MainWindow", "Newton[°N]"))
        item = out_convert_list.item(21)
        item.setText(_translate("MainWindow", "Réaumur[°Ré]"))